# Generated by Django 5.1.2 on 2024-11-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
