# Generated by Django 5.1.2 on 2024-11-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_images_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='status',
            field=models.CharField(choices=[('first', 'published'), ('second', 'draft')], default='second', max_length=100),
        ),
    ]
