# Generated by Django 5.1.2 on 2024-12-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_pageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='ip',
            field=models.GenericIPAddressField(default=0),
        ),
    ]
