# Generated by Django 5.1.2 on 2024-12-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_pageview_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
    ]
