# Generated by Django 5.1.2 on 2024-12-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_like_is_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='artical',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='like',
            name='page_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='like',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
