# Generated by Django 5.1.2 on 2024-12-07 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_answercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='answercomment',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='SaveArtical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('artical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.artical')),
            ],
        ),
    ]
