# Generated by Django 5.1.2 on 2024-12-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_saveartical_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveartical',
            name='save',
            field=models.BooleanField(default=True),
        ),
    ]
