# Generated by Django 5.1.2 on 2024-12-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_saveartical_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveartical',
            old_name='save',
            new_name='saved',
        ),
    ]
