# Generated by Django 5.1.2 on 2024-12-07 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_save_saveartical_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveartical',
            name='artical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.images'),
        ),
    ]
