# Generated by Django 5.1.2 on 2024-11-25 13:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_loginattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
